Repository mitodl/odl-video-service, pull requests merged in 2018-03, with the labels that each got.

#455 Update django-server-status version to 0.5.0
  requirements.in
  requirements.txt
Labels: Needs Review

#446 TechTV caption import
  app.json
  requirements.in
  requirements.txt
  techtv2ovs/management/commands/techtvimport.py
  techtv2ovs/utils.py
  techtv2ovs/utils_test.py
Labels: Waiting on Author

#459 Join BASE_DIR for STATIC_ROOT
  odl_video/settings.py
Labels: Waiting on Author

#466 Added a check to verify that file has not already been synced
  s3_sync/s3_sync.py
  s3_sync/s3_sync_settings.ini
Labels: DevOps, Needs Review

#464 Force login on protected video URL's but not public video URL's
  odl_video/settings.py
  ui/views.py
  ui/views_test.py
Labels: Waiting on Author

#454 Import public TechTV collections and set video stream source
  cloudsync/tasks_test.py
  cloudsync/youtube.py
  techtv2ovs/management/commands/techtvimport.py
  techtv2ovs/utils.py
  techtv2ovs/utils_test.py
  ui/constants.py
  ui/migrations/0016_collection_stream_source.py
  ui/models.py
  ui/signals.py
  ui/signals_test.py
  ui/views_test.py
Labels: Waiting on Author

#465 Upgrade to Django 1.11
  conftest.py
  odl_video/settings.py
  pylintrc
  pytest.ini
  requirements.in
  requirements.txt
  techtv2ovs/utils.py
  ui/api_test.py
  ui/permissions_test.py
  ui/templatetags/render_bundle.py
  ui/urls.py
  ui/utils.py
  ui/views.py
  ui/views_test.py
Labels: Waiting on Author

#469 Made the message posted in slack a bit more verbose for clarity
  s3_sync/s3_sync.py
Labels: DevOps, Needs Review

#471 Custom quality selector function for videojs
  static/js/components/VideoPlayer.js
  static/js/components/VideoPlayer_test.js
Labels: Waiting on Author

#460 VideoJS YouTube Player
  cloudsync/tasks_test.py
  package.json
  static/js/components/VideoPlayer.js
  static/js/components/VideoPlayer_test.js
  static/js/factories/video.js
  static/js/flow/videoTypes.js
  static/js/global_init.js
  static/js/lib/video.js
  static/scss/videoPlayer.scss
  ui/models.py
  ui/models_test.py
  ui/serializers.py
  ui/serializers_test.py
  yarn.lock
Labels: Needs Review

#476 Upload to youtube via daily celery task instead of signal
  .env.example
  app.json
  cloudsync/tasks.py
  cloudsync/tasks_test.py
  cloudsync/youtube.py
  odl_video/settings.py
  ui/signals.py
  ui/signals_test.py
Labels: Waiting on Author

#477 Show the encode job associated with each video in Admin
  ui/admin.py
Labels: Waiting on Author

#478 Switch from celery.get_task_logger() to logging.getLogger() for tasks
  cloudsync/tasks.py
  cloudsync/youtube.py
  techtv2ovs/tasks.py
Labels: Waiting on Author

#481 Don't try to save EncodeJobs on the video admin page
  ui/admin.py
Labels: Waiting on Author

#485 Correctly assign attributes to VideoSubtitles imported from TechTV
  techtv2ovs/utils.py
  techtv2ovs/utils_test.py
  ui/models.py
Labels: Waiting on Author

#492 Add UserMetadata section w/environment id in transcode jobs
  cloudsync/api.py
  cloudsync/api_test.py
  cloudsync/tasks_test.py
Labels: Waiting on Author
