Repository mitodl/odl-video-service, pull requests merged in 2018-05, with the labels that each got.

#571 Dorska/collection 403
  static/js/components/errorMessages.js
  static/js/containers/CollectionDetailPage.js
  static/js/containers/CollectionDetailPage_test.js
  static/js/containers/CollectionListPage.js
Labels: Waiting on Author

#576 add additional empty check when rendering analytics chart
  static/js/components/analytics/AnalyticsChart.js
Labels: Waiting on Author

#581 anonymize help page
  ui/views.py
  ui/views_test.py
Labels: Waiting on Author

#575 adding toast message to EditVideoFormDialog
  static/js/components/dialogs/EditVideoFormDialog.js
  static/js/components/dialogs/EditVideoFormDialog_test.js
Labels: Waiting on Author

#588 one more check for empty dimensions/padding in analytics chart
  static/js/components/analytics/AnalyticsChart.js
Labels: Waiting on Author

#580 add contact us link to footer, fix email address var in error messages
  static/js/components/Footer.js
  static/js/components/Footer_test.js
  static/js/components/errorMessages.js
Labels: Waiting on Author

#579 add toast messages for collection created/updated
  static/js/components/dialogs/CollectionFormDialog.js
  static/js/components/dialogs/CollectionFormDialog_test.js
Labels: Waiting on Author

#574 send debug emails to support for certain notification emails
  mail/tasks.py
  mail/tasks_test.py
Labels: Waiting on Author

#586 hides logout button when there is logged in user
  static/js/components/material/Drawer.js
  static/js/components/material/Drawer_test.js
Labels: Waiting on Author

#582 Dorsk/toast subtitle upload
  static/js/containers/VideoDetailPage.js
  static/js/containers/VideoDetailPage_test.js
Labels: Waiting on Author

#594 Don't change fluid property when switching playback source
  static/js/components/VideoPlayer.js
Labels: Waiting on Author

#587 Per-user moira list cache
  app.json
  odl_video/settings.py
  ui/models.py
  ui/signals.py
  ui/utils.py
  ui/utils_test.py
  ui/views_test.py
Labels: Waiting on Author

#590 Dorska/subtitles deletion modal
  static/js/actions/videoUi.js
  static/js/components/VideoSubtitleCard.js
  static/js/components/dialogs/DeleteSubtitlesDialog.js
  static/js/components/dialogs/DeleteSubtitlesDialog_test.js
  static/js/constants.js
  static/js/containers/VideoDetailPage.js
  static/js/containers/VideoDetailPage_test.js
  static/js/flow/videoTypes.js
  static/js/reducers/videoUi.js
  static/js/reducers/videoUi_test.js
Labels: Waiting on Author

#597 add video count to collection items in drawer
  static/js/components/material/Drawer.js
  static/js/components/material/Drawer_test.js
Labels: Waiting on Author

#600 add status messages to embed page
  static/js/containers/VideoEmbedPage.js
  static/js/containers/VideoEmbedPage_test.js
Labels: Needs Review

#602 Decouple watch bucket uploads from collection titles
  cloudsync/api.py
  cloudsync/api_test.py
  ui/migrations/0020_collection_name.py
  ui/models.py
Labels: Waiting on Author

#599 add django-hijack for user masquerading
  odl_video/settings.py
  odl_video/urls.py
  requirements.txt
  ui/templates/base.html
Labels: Waiting on Author

#605 Dorska/analytics close button
  static/js/containers/VideoAnalyticsOverlay.js
  static/js/containers/VideoAnalyticsOverlay_test.js
  static/js/containers/VideoDetailPage.js
  static/js/containers/VideoDetailPage_test.js
  static/scss/generalStyles.scss
Labels: Waiting on Author

#610 remove collections button from drawer, linkify drawer header
  static/js/components/material/Drawer.js
  static/js/components/material/Drawer_test.js
Labels: Waiting on Author

#607 analytics style tweaks
  static/js/components/analytics/AnalyticsChart.js
  static/js/components/analytics/AnalyticsInfoTable.js
  static/js/components/analytics/AnalyticsPane.js
  static/js/components/analytics/ProgressSlider.js
  static/js/containers/VideoAnalyticsOverlay.js
  static/js/containers/VideoDetailPage.js
Labels: Needs Review

#611 change 'Only me' => 'Only owner', to clarify permissions behavior
  static/js/components/dialogs/CollectionFormDialog.js
  static/js/components/dialogs/EditVideoFormDialog.js
  static/scss/generalStyles.scss
Labels: Waiting on Author

#612 ignore transcode exceptions for deleted videos
  cloudsync/exceptions.py
  cloudsync/tasks.py
  cloudsync/tasks_test.py
  odl_video/settings.py
Labels: Needs Review

#613 add collection_key to SimpleVideoSerializer
  ui/serializers.py
  ui/serializers_test.py
Labels: Waiting on Author, bug

#608 Dorska/analytics width
  static/js/components/VideoPlayer.js
  static/js/components/VideoPlayer_test.js
  static/js/containers/VideoDetailPage.js
  static/js/containers/VideoDetailPage_test.js
Labels: Waiting on Author

#616 Bring back the login view and make it the default LOGIN_URL
  odl_video/settings.py
  ui/templates/registration/login.html
  ui/urls.py
  ui/views.py
Labels: Waiting on Author

#609 Don't require login for 404 collection URLs
  ui/views.py
  ui/views_test.py
Labels: Waiting on Author

#619 update error message for 404
  static/js/containers/ErrorPage.js
  static/js/containers/ErrorPage_test.js
Labels: Waiting on Author

#621 Fix login redirect
  ui/templates/registration/login.html
  ui/views.py
  ui/views_test.py
Labels: Needs Review

#625 Dorska/use moira user list membership
  requirements.txt
  ui/conftest.py
  ui/models.py
  ui/permissions_test.py
  ui/utils.py
  ui/utils_test.py
  ui/views_test.py
Labels: Waiting on Author

#626 pagination styling
  static/js/components/Paginator.js
  static/js/containers/CollectionListPage.js
  static/scss/collection.scss
  static/scss/paginator.scss
Labels: Waiting on Author

#627 restore videofile_set to serializer
  ui/serializers.py
  ui/serializers_test.py
Labels: Waiting on Author

#622 add videos pagination backend
  odl_video/settings.py
  ui/factories.py
  ui/models.py
  ui/pagination.py
  ui/views.py
  ui/views_test.py
Labels: Waiting on Author

#628 refactoring CollectionDetail, in preparation for videos pagination
  static/js/components/VideoCard.js
  static/js/components/VideoCard_test.js
  static/js/components/VideoList.js
  static/js/components/VideoList_test.js
  static/js/containers/CollectionDetailPage.js
  static/js/containers/CollectionDetailPage_test.js
Labels: Waiting on Author

#632 Update version for mit-moira
  requirements.in
  requirements.txt
Labels: Needs Review

#635 Fix permissions issue with anonymous users and public videos
  ui/models.py
  ui/utils.py
  ui/utils_test.py
  ui/views_test.py
Labels: Needs Review

#642 Public video download links
  ui/models.py
  ui/models_test.py
  ui/urls.py
  ui/views.py
  ui/views_test.py
Labels: Waiting on Author
