Repository mitodl/odl-video-service, pull requests merged in 2019-08, with the labels that each got.

#763 Added request to auto-add HLS videos to edX when appropriate
  Dockerfile-nb
  app.json
  cloudsync/conftest.py
  conftest.py
  docker-compose-notebook.yml
  mail/api_test.py
  odl_video/settings.py
  ui/admin.py
  ui/api.py
  ui/api_test.py
  ui/conftest.py
  ui/management/commands/add_hls_video_to_edx.py
  ui/migrations/0024_add_collection_edx_course_id.py
  ui/models.py
  ui/models_test.py
  ui/signals.py
  ui/signals_test.py
  ui/tasks.py
  ui/tasks_test.py
  ui/utils.py
  ui/utils_test.py
Labels: Waiting on Author

#767 Changed edX auto-add to use edxval library endpoints
  app.json
  odl_video/settings.py
  odl_video/test_utils.py
  ui/api.py
  ui/api_test.py
  ui/utils.py
Labels: Needs Review

#770 Upgrade Django to 2.1.11
  requirements.in
  requirements.txt
Labels: Waiting on Author

#775 Remove -e flags in requirements.txt
  requirements.txt
Labels: Waiting on Author

#778 Added runtime.txt to specify python version
  runtime.txt
Labels: DevOps
