Repository mitodl/odl-video-service, pull requests merged in 2020-09, with the labels that each got.

#877 Delete NotificationEmail
  mail/admin.py
  mail/migrations/0005_delete_notificationemail.py
  mail/models.py
Labels: Needs Review

#909 Make collection autocomplete field for video
  ui/admin.py
Labels: Waiting on Author

#910 Bumped to latest django-server-status
  requirements.in
  requirements.txt
Labels: DevOps, Waiting on Author

#789 add github templates copied from mitxpro
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/config_change_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/pull_request_template.md
  pull_request_template.md
Labels: Waiting on Author

#913 accessibility link in the footer
  static/js/components/Footer.js
  static/js/components/Footer_test.js
Labels: Waiting on Author
