Repository mitodl/odl-video-service, pull requests merged in 2023-01, with the labels that each got.

#1028 Only upload videos to edx if the collection defines course ID
  ui/signals.py
  ui/signals_test.py
Labels: Waiting on Author

#1030 call the celery task as async
  ui/api.py
  ui/signals.py
Labels: Waiting on Author

#1025 Update production dockerfile build with static asset compilation
  Dockerfile
  odl_video/settings.py
  ui/apps.py
Labels: Waiting on Author, Work in Progress

#1032 Reorganizing the Dockerfile a bit to be a little more coherent. Remov…
  Dockerfile
Labels: enhancement, DevOps, Waiting on Author, Tech Debt, deploying to rc

#1041 Disable notification to application admin email for corrupt videos
  mail/constants.py
Labels: Waiting on Author
